disabled_rules:
  - trailing_comma

opt_in_rules:
  - closure_end_indentation
  - closure_spacing

line_length:
  warning: 150
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

trailing_comma:
  mandatory_comma: true

cyclomatic_complexity:
  ignores_case_statements: true

identifier_name:
  excluded:
    - id
